---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment"

- name: Configure mongo
  template: 
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongo
...
